#!/bin/sh
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_indep_pR --seed=0 --hmdp_name=hmdp1.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_indep_pR --seed=1 --hmdp_name=hmdp1.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_indep_pR --seed=2 --hmdp_name=hmdp1.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_indep_pR --seed=3 --hmdp_name=hmdp1.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_indep_pR --seed=4 --hmdp_name=hmdp1.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_indep_pR --seed=5 --hmdp_name=hmdp1.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_indep_pR --seed=6 --hmdp_name=hmdp1.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_indep_pR --seed=7 --hmdp_name=hmdp1.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_indep_pR --seed=8 --hmdp_name=hmdp1.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_indep_pR --seed=9 --hmdp_name=hmdp1.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_indep_pR --seed=10 --hmdp_name=hmdp1.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_indep_pR --seed=11 --hmdp_name=hmdp1.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_indep_pR --seed=12 --hmdp_name=hmdp1.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_indep_pR --seed=13 --hmdp_name=hmdp1.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_indep_pR --seed=14 --hmdp_name=hmdp1.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_indep_pR --seed=15 --hmdp_name=hmdp1.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_indep_pR --seed=16 --hmdp_name=hmdp1.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_indep_pR --seed=17 --hmdp_name=hmdp1.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_indep_pR --seed=18 --hmdp_name=hmdp1.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_indep_pR --seed=19 --hmdp_name=hmdp1.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_indep_pR --seed=20 --hmdp_name=hmdp1.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_indep_pR --seed=21 --hmdp_name=hmdp1.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_indep_pR --seed=22 --hmdp_name=hmdp1.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_indep_pR --seed=23 --hmdp_name=hmdp1.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_indep_pR --seed=24 --hmdp_name=hmdp1.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_indep_pR --seed=25 --hmdp_name=hmdp1.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_indep_pR --seed=26 --hmdp_name=hmdp1.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_indep_pR --seed=27 --hmdp_name=hmdp1.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_indep_pR --seed=28 --hmdp_name=hmdp1.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_indep_pR --seed=29 --hmdp_name=hmdp1.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_avoid_pR --seed=30 --hmdp_name=hmdp1.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_avoid_pR --seed=31 --hmdp_name=hmdp1.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_avoid_pR --seed=32 --hmdp_name=hmdp1.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_avoid_pR --seed=33 --hmdp_name=hmdp1.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_avoid_pR --seed=34 --hmdp_name=hmdp1.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_avoid_pR --seed=35 --hmdp_name=hmdp1.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_avoid_pR --seed=36 --hmdp_name=hmdp1.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_avoid_pR --seed=37 --hmdp_name=hmdp1.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_avoid_pR --seed=38 --hmdp_name=hmdp1.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_avoid_pR --seed=39 --hmdp_name=hmdp1.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_avoid_pR --seed=40 --hmdp_name=hmdp1.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_avoid_pR --seed=41 --hmdp_name=hmdp1.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_avoid_pR --seed=42 --hmdp_name=hmdp1.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_avoid_pR --seed=43 --hmdp_name=hmdp1.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_avoid_pR --seed=44 --hmdp_name=hmdp1.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_avoid_pR --seed=45 --hmdp_name=hmdp1.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_avoid_pR --seed=46 --hmdp_name=hmdp1.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_avoid_pR --seed=47 --hmdp_name=hmdp1.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_avoid_pR --seed=48 --hmdp_name=hmdp1.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_avoid_pR --seed=49 --hmdp_name=hmdp1.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_avoid_pR --seed=50 --hmdp_name=hmdp1.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_avoid_pR --seed=51 --hmdp_name=hmdp1.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_avoid_pR --seed=52 --hmdp_name=hmdp1.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_avoid_pR --seed=53 --hmdp_name=hmdp1.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_avoid_pR --seed=54 --hmdp_name=hmdp1.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_avoid_pR --seed=55 --hmdp_name=hmdp1.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_avoid_pR --seed=56 --hmdp_name=hmdp1.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_avoid_pR --seed=57 --hmdp_name=hmdp1.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_avoid_pR --seed=58 --hmdp_name=hmdp1.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_avoid_pR --seed=59 --hmdp_name=hmdp1.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_move_to_pR --seed=60 --hmdp_name=hmdp1.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_move_to_pR --seed=61 --hmdp_name=hmdp1.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_move_to_pR --seed=62 --hmdp_name=hmdp1.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_move_to_pR --seed=63 --hmdp_name=hmdp1.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_move_to_pR --seed=64 --hmdp_name=hmdp1.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_move_to_pR --seed=65 --hmdp_name=hmdp1.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_move_to_pR --seed=66 --hmdp_name=hmdp1.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_move_to_pR --seed=67 --hmdp_name=hmdp1.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_move_to_pR --seed=68 --hmdp_name=hmdp1.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_move_to_pR --seed=69 --hmdp_name=hmdp1.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_move_to_pR --seed=70 --hmdp_name=hmdp1.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_move_to_pR --seed=71 --hmdp_name=hmdp1.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_move_to_pR --seed=72 --hmdp_name=hmdp1.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_move_to_pR --seed=73 --hmdp_name=hmdp1.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_move_to_pR --seed=74 --hmdp_name=hmdp1.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_move_to_pR --seed=75 --hmdp_name=hmdp1.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_move_to_pR --seed=76 --hmdp_name=hmdp1.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_move_to_pR --seed=77 --hmdp_name=hmdp1.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_move_to_pR --seed=78 --hmdp_name=hmdp1.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_move_to_pR --seed=79 --hmdp_name=hmdp1.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_move_to_pR --seed=80 --hmdp_name=hmdp1.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_move_to_pR --seed=81 --hmdp_name=hmdp1.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_move_to_pR --seed=82 --hmdp_name=hmdp1.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_move_to_pR --seed=83 --hmdp_name=hmdp1.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_move_to_pR --seed=84 --hmdp_name=hmdp1.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_move_to_pR --seed=85 --hmdp_name=hmdp1.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_move_to_pR --seed=86 --hmdp_name=hmdp1.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_move_to_pR --seed=87 --hmdp_name=hmdp1.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_move_to_pR --seed=88 --hmdp_name=hmdp1.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_move_to_pR --seed=89 --hmdp_name=hmdp1.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_indep_pR --seed=0 --hmdp_name=hmdp2.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_indep_pR --seed=1 --hmdp_name=hmdp2.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_indep_pR --seed=2 --hmdp_name=hmdp2.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_indep_pR --seed=3 --hmdp_name=hmdp2.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_indep_pR --seed=4 --hmdp_name=hmdp2.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_indep_pR --seed=5 --hmdp_name=hmdp2.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_indep_pR --seed=6 --hmdp_name=hmdp2.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_indep_pR --seed=7 --hmdp_name=hmdp2.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_indep_pR --seed=8 --hmdp_name=hmdp2.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_indep_pR --seed=9 --hmdp_name=hmdp2.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_indep_pR --seed=10 --hmdp_name=hmdp2.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_indep_pR --seed=11 --hmdp_name=hmdp2.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_indep_pR --seed=12 --hmdp_name=hmdp2.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_indep_pR --seed=13 --hmdp_name=hmdp2.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_indep_pR --seed=14 --hmdp_name=hmdp2.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_indep_pR --seed=15 --hmdp_name=hmdp2.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_indep_pR --seed=16 --hmdp_name=hmdp2.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_indep_pR --seed=17 --hmdp_name=hmdp2.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_indep_pR --seed=18 --hmdp_name=hmdp2.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_indep_pR --seed=19 --hmdp_name=hmdp2.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_indep_pR --seed=20 --hmdp_name=hmdp2.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_indep_pR --seed=21 --hmdp_name=hmdp2.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_indep_pR --seed=22 --hmdp_name=hmdp2.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_indep_pR --seed=23 --hmdp_name=hmdp2.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_indep_pR --seed=24 --hmdp_name=hmdp2.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_indep_pR --seed=25 --hmdp_name=hmdp2.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_indep_pR --seed=26 --hmdp_name=hmdp2.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_indep_pR --seed=27 --hmdp_name=hmdp2.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_indep_pR --seed=28 --hmdp_name=hmdp2.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_indep_pR --seed=29 --hmdp_name=hmdp2.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_avoid_pR --seed=30 --hmdp_name=hmdp2.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_avoid_pR --seed=31 --hmdp_name=hmdp2.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_avoid_pR --seed=32 --hmdp_name=hmdp2.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_avoid_pR --seed=33 --hmdp_name=hmdp2.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_avoid_pR --seed=34 --hmdp_name=hmdp2.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_avoid_pR --seed=35 --hmdp_name=hmdp2.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_avoid_pR --seed=36 --hmdp_name=hmdp2.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_avoid_pR --seed=37 --hmdp_name=hmdp2.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_avoid_pR --seed=38 --hmdp_name=hmdp2.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_avoid_pR --seed=39 --hmdp_name=hmdp2.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_avoid_pR --seed=40 --hmdp_name=hmdp2.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_avoid_pR --seed=41 --hmdp_name=hmdp2.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_avoid_pR --seed=42 --hmdp_name=hmdp2.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_avoid_pR --seed=43 --hmdp_name=hmdp2.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_avoid_pR --seed=44 --hmdp_name=hmdp2.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_avoid_pR --seed=45 --hmdp_name=hmdp2.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_avoid_pR --seed=46 --hmdp_name=hmdp2.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_avoid_pR --seed=47 --hmdp_name=hmdp2.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_avoid_pR --seed=48 --hmdp_name=hmdp2.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_avoid_pR --seed=49 --hmdp_name=hmdp2.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_avoid_pR --seed=50 --hmdp_name=hmdp2.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_avoid_pR --seed=51 --hmdp_name=hmdp2.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_avoid_pR --seed=52 --hmdp_name=hmdp2.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_avoid_pR --seed=53 --hmdp_name=hmdp2.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_avoid_pR --seed=54 --hmdp_name=hmdp2.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_avoid_pR --seed=55 --hmdp_name=hmdp2.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_avoid_pR --seed=56 --hmdp_name=hmdp2.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_avoid_pR --seed=57 --hmdp_name=hmdp2.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_avoid_pR --seed=58 --hmdp_name=hmdp2.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_avoid_pR --seed=59 --hmdp_name=hmdp2.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_move_to_pR --seed=60 --hmdp_name=hmdp2.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_move_to_pR --seed=61 --hmdp_name=hmdp2.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_move_to_pR --seed=62 --hmdp_name=hmdp2.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_move_to_pR --seed=63 --hmdp_name=hmdp2.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_move_to_pR --seed=64 --hmdp_name=hmdp2.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_move_to_pR --seed=65 --hmdp_name=hmdp2.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_move_to_pR --seed=66 --hmdp_name=hmdp2.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_move_to_pR --seed=67 --hmdp_name=hmdp2.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_move_to_pR --seed=68 --hmdp_name=hmdp2.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_move_to_pR --seed=69 --hmdp_name=hmdp2.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_move_to_pR --seed=70 --hmdp_name=hmdp2.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_move_to_pR --seed=71 --hmdp_name=hmdp2.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_move_to_pR --seed=72 --hmdp_name=hmdp2.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_move_to_pR --seed=73 --hmdp_name=hmdp2.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_move_to_pR --seed=74 --hmdp_name=hmdp2.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_move_to_pR --seed=75 --hmdp_name=hmdp2.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_move_to_pR --seed=76 --hmdp_name=hmdp2.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_move_to_pR --seed=77 --hmdp_name=hmdp2.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_move_to_pR --seed=78 --hmdp_name=hmdp2.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_move_to_pR --seed=79 --hmdp_name=hmdp2.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_move_to_pR --seed=80 --hmdp_name=hmdp2.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_move_to_pR --seed=81 --hmdp_name=hmdp2.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_move_to_pR --seed=82 --hmdp_name=hmdp2.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_move_to_pR --seed=83 --hmdp_name=hmdp2.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_move_to_pR --seed=84 --hmdp_name=hmdp2.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_move_to_pR --seed=85 --hmdp_name=hmdp2.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_move_to_pR --seed=86 --hmdp_name=hmdp2.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_move_to_pR --seed=87 --hmdp_name=hmdp2.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_move_to_pR --seed=88 --hmdp_name=hmdp2.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_move_to_pR --seed=89 --hmdp_name=hmdp2.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_indep_pR --seed=0 --hmdp_name=hmdp3.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_indep_pR --seed=1 --hmdp_name=hmdp3.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_indep_pR --seed=2 --hmdp_name=hmdp3.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_indep_pR --seed=3 --hmdp_name=hmdp3.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_indep_pR --seed=4 --hmdp_name=hmdp3.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_indep_pR --seed=5 --hmdp_name=hmdp3.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_indep_pR --seed=6 --hmdp_name=hmdp3.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_indep_pR --seed=7 --hmdp_name=hmdp3.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_indep_pR --seed=8 --hmdp_name=hmdp3.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_indep_pR --seed=9 --hmdp_name=hmdp3.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_indep_pR --seed=10 --hmdp_name=hmdp3.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_indep_pR --seed=11 --hmdp_name=hmdp3.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_indep_pR --seed=12 --hmdp_name=hmdp3.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_indep_pR --seed=13 --hmdp_name=hmdp3.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_indep_pR --seed=14 --hmdp_name=hmdp3.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_indep_pR --seed=15 --hmdp_name=hmdp3.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_indep_pR --seed=16 --hmdp_name=hmdp3.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_indep_pR --seed=17 --hmdp_name=hmdp3.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_indep_pR --seed=18 --hmdp_name=hmdp3.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_indep_pR --seed=19 --hmdp_name=hmdp3.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_indep_pR --seed=20 --hmdp_name=hmdp3.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_indep_pR --seed=21 --hmdp_name=hmdp3.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_indep_pR --seed=22 --hmdp_name=hmdp3.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_indep_pR --seed=23 --hmdp_name=hmdp3.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_indep_pR --seed=24 --hmdp_name=hmdp3.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_indep_pR --seed=25 --hmdp_name=hmdp3.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_indep_pR --seed=26 --hmdp_name=hmdp3.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_indep_pR --seed=27 --hmdp_name=hmdp3.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_indep_pR --seed=28 --hmdp_name=hmdp3.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_indep_pR --seed=29 --hmdp_name=hmdp3.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_avoid_pR --seed=30 --hmdp_name=hmdp3.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_avoid_pR --seed=31 --hmdp_name=hmdp3.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_avoid_pR --seed=32 --hmdp_name=hmdp3.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_avoid_pR --seed=33 --hmdp_name=hmdp3.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_avoid_pR --seed=34 --hmdp_name=hmdp3.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_avoid_pR --seed=35 --hmdp_name=hmdp3.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_avoid_pR --seed=36 --hmdp_name=hmdp3.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_avoid_pR --seed=37 --hmdp_name=hmdp3.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_avoid_pR --seed=38 --hmdp_name=hmdp3.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_avoid_pR --seed=39 --hmdp_name=hmdp3.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_avoid_pR --seed=40 --hmdp_name=hmdp3.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_avoid_pR --seed=41 --hmdp_name=hmdp3.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_avoid_pR --seed=42 --hmdp_name=hmdp3.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_avoid_pR --seed=43 --hmdp_name=hmdp3.yaml
python3 run_mpc_iterations_experiments.py --pR_mode=CA_SI --task=coll_avoid --pH_mode=pH_avoid_pR --seed=44 --hmdp_name=hmdp3.yaml
